[package]
name = "snowball_server"
version = "0.1.0"
authors = []
edition = '2018'

[dependencies]
tungstenite = "0.6.1"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
rand = "0.6.4"

